FROM jenkins/inbound-agent:3301.v4363ddcca_4e7-3

USER root

ENV MAVEN_VERSION=3.9.9 \
    MAVEN_HOME=/usr/share/maven \
    JDK_VERSION=-11.0.27+6

ENV PATH=${MAVEN_HOME}/bin:${PATH}

ADD apache-maven-3.9.9-bin.tar.gz .
ADD OpenJDK11U-jdk_x64_linux_hotspot_11.0.27_6.tar.gz .
ADD active-jdk11.sh /opt

RUN mv apache-maven-${MAVEN_VERSION} $MAVEN_HOME && \
    mv jdk${JDK_VERSION} /opt/jdk11

USER jenkins