FROM harbor.idc.roywong.work/quay.io/argoproj/argocd:v2.12.1

LABEL AUTHOR="WangHaoHao" \
      DESCRIPTION="自定义argocd系统，在原始镜基础上安装jsonnet。"

ADD go-jsonnet_0.21.0_Linux_x86_64.tar.gz /usr/local/bin
ADD yq_linux_amd64.tar.gz /usr/local/bin